/*
-----------------------------------------------------
SQLITEContractGen.py 2.0

This file was autogenerated with run cmd:
  "SQLITEContractGen.py --packagename=org.frc836.database --classname=FRCScoutingContract --infile=FRC_Scouting_Server/scouting.sql --outfile=src/org/frc836/database/FRCScoutingContract.java"

python version info:
  2.7.3 (default, Sep 26 2013, 20:03:06)
[GCC 4.6.3]

Please take heed of modifying unnecessarily
-----------------------------------------------------
*/

package org.frc3260.database;

import android.provider.BaseColumns;

public final class FRCScoutingContract
{
    public FRCScoutingContract()
    {
    }

	;

    public static abstract class CONFIGURATION_LU_Entry implements BaseColumns
    {
        public static final String TABLE_NAME = "configuration_lu";
        public static final String COLUMN_NAME_ID = "id";
        public static final String COLUMN_NAME_CONFIGURATION_DESC = "configuration_desc";
        public static final String COLUMN_NAME_TIMESTAMP = "timestamp";
        public static final String COLUMN_NAME_INVALID = "invalid";
    }

    public static abstract class EVENT_LU_Entry implements BaseColumns
    {
        public static final String TABLE_NAME = "event_lu";
        public static final String COLUMN_NAME_ID = "id";
        public static final String COLUMN_NAME_EVENT_NAME = "event_name";
        public static final String COLUMN_NAME_MATCH_URL = "match_url";
        public static final String COLUMN_NAME_TIMESTAMP = "timestamp";
        public static final String COLUMN_NAME_INVALID = "invalid";
    }

    public static abstract class FACT_CYCLE_DATA_Entry implements BaseColumns
    {
        public static final String TABLE_NAME = "fact_cycle_data";
        public static final String COLUMN_NAME_ID = "id";
        public static final String COLUMN_NAME_EVENT_ID = "event_id";
        public static final String COLUMN_NAME_MATCH_ID = "match_id";
        public static final String COLUMN_NAME_TEAM_ID = "team_id";
        public static final String COLUMN_NAME_CYCLE_NUM = "cycle_num";
        public static final String COLUMN_NAME_NEAR_POSS = "near_poss";
        public static final String COLUMN_NAME_WHITE_POSS = "white_poss";
        public static final String COLUMN_NAME_FAR_POSS = "far_poss";
        public static final String COLUMN_NAME_TRUSS = "truss";
        public static final String COLUMN_NAME_CATCH = "catch";
        public static final String COLUMN_NAME_HIGH = "high";
        public static final String COLUMN_NAME_LOW = "low";
        public static final String COLUMN_NAME_ASSISTS = "assists";
        public static final String COLUMN_NAME_TIMESTAMP = "timestamp";
        public static final String COLUMN_NAME_INVALID = "invalid";
    }

    public static abstract class FACT_MATCH_DATA_Entry implements BaseColumns
    {
        public static final String TABLE_NAME = "fact_match_data";
        public static final String COLUMN_NAME_ID = "id";
        public static final String COLUMN_NAME_EVENT_ID = "event_id";
        public static final String COLUMN_NAME_MATCH_ID = "match_id";
        public static final String COLUMN_NAME_TEAM_ID = "team_id";
        public static final String COLUMN_NAME_AUTO_HIGH = "auto_high";
        public static final String COLUMN_NAME_AUTO_HIGH_HOT = "auto_high_hot";
        public static final String COLUMN_NAME_AUTO_LOW = "auto_low";
        public static final String COLUMN_NAME_AUTO_LOW_HOT = "auto_low_hot";
		public static final String COLUMN_NAME_ASSIST_POINTS = "assist_points";
        public static final String COLUMN_NAME_HIGH = "high";
        public static final String COLUMN_NAME_LOW = "low";
		public static final String COLUMN_NAME_TRUSS = "truss";
		public static final String COLUMN_NAME_CAUGHT = "caught";
		public static final String COLUMN_NAME_AUTO_MOBILE = "auto_mobile";
        public static final String COLUMN_NAME_AUTO_GOALIE = "auto_goalie";
        public static final String COLUMN_NAME_NUM_CYCLES = "num_cycles";
        public static final String COLUMN_NAME_MISSES = "misses";
        public static final String COLUMN_NAME_FOUL = "foul";
        public static final String COLUMN_NAME_TECH_FOUL = "tech_foul";
        public static final String COLUMN_NAME_TIP_OVER = "tip_over";
        public static final String COLUMN_NAME_YELLOW_CARD = "yellow_card";
        public static final String COLUMN_NAME_RED_CARD = "red_card";
        public static final String COLUMN_NAME_NOTES = "notes";
        public static final String COLUMN_NAME_TIMESTAMP = "timestamp";
        public static final String COLUMN_NAME_INVALID = "invalid";
    }

    public static abstract class NOTES_OPTIONS_Entry implements BaseColumns
    {
        public static final String TABLE_NAME = "notes_options";
        public static final String COLUMN_NAME_ID = "id";
        public static final String COLUMN_NAME_OPTION_TEXT = "option_text";
        public static final String COLUMN_NAME_TIMESTAMP = "timestamp";
        public static final String COLUMN_NAME_INVALID = "invalid";
    }

    public static abstract class ROBOT_LU_Entry implements BaseColumns
    {
        public static final String TABLE_NAME = "robot_lu";
        public static final String COLUMN_NAME_ID = "id";
        public static final String COLUMN_NAME_TEAM_ID = "team_id";
        public static final String COLUMN_NAME_ROBOT_PHOTO = "robot_photo";
        public static final String COLUMN_NAME_TIMESTAMP = "timestamp";
        public static final String COLUMN_NAME_INVALID = "invalid";
    }

    public static abstract class SCOUT_PIT_DATA_Entry implements BaseColumns
    {
        public static final String TABLE_NAME = "scout_pit_data";
        public static final String COLUMN_NAME_ID = "id";
        public static final String COLUMN_NAME_TEAM_ID = "team_id";
        public static final String COLUMN_NAME_CONFIGURATION_ID = "configuration_id";
        public static final String COLUMN_NAME_WHEEL_TYPE_ID = "wheel_type_id";
        public static final String COLUMN_NAME_WHEEL_BASE_ID = "wheel_base_id";
        public static final String COLUMN_NAME_AUTONOMOUS_MODE = "autonomous_mode";
        public static final String COLUMN_NAME_AUTO_HIGH = "auto_high";
        public static final String COLUMN_NAME_AUTO_LOW = "auto_low";
        public static final String COLUMN_NAME_AUTO_HOT = "auto_hot";
        public static final String COLUMN_NAME_AUTO_MOBILE = "auto_mobile";
        public static final String COLUMN_NAME_AUTO_GOALIE = "auto_goalie";
        public static final String COLUMN_NAME_TRUSS = "truss";
        public static final String COLUMN_NAME_CATCH = "catch";
        public static final String COLUMN_NAME_ACTIVE_CONTROL = "active_control";
        public static final String COLUMN_NAME_LAUNCH_BALL = "launch_ball";
        public static final String COLUMN_NAME_SCORE_HIGH = "score_high";
        public static final String COLUMN_NAME_SCORE_LOW = "score_low";
        public static final String COLUMN_NAME_MAX_HEIGHT = "max_height";
        public static final String COLUMN_NAME_SCOUT_COMMENTS = "scout_comments";
        public static final String COLUMN_NAME_TIMESTAMP = "timestamp";
        public static final String COLUMN_NAME_INVALID = "invalid";
    }

    public static abstract class WHEEL_BASE_LU_Entry implements BaseColumns
    {
        public static final String TABLE_NAME = "wheel_base_lu";
        public static final String COLUMN_NAME_ID = "id";
        public static final String COLUMN_NAME_WHEEL_BASE_DESC = "wheel_base_desc";
        public static final String COLUMN_NAME_TIMESTAMP = "timestamp";
        public static final String COLUMN_NAME_INVALID = "invalid";
    }

    public static abstract class WHEEL_TYPE_LU_Entry implements BaseColumns
    {
        public static final String TABLE_NAME = "wheel_type_lu";
        public static final String COLUMN_NAME_ID = "id";
        public static final String COLUMN_NAME_WHEEL_TYPE_DESC = "wheel_type_desc";
        public static final String COLUMN_NAME_TIMESTAMP = "timestamp";
        public static final String COLUMN_NAME_INVALID = "invalid";
    }

    public static final String[] SQL_CREATE_ENTRIES = {
            "CREATE TABLE IF NOT EXISTS configuration_lu (\n" +
            "	id integer primary key autoincrement,\n" +
            "	configuration_desc text NOT NULL,\n" +
            "	timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\n" +
            "	invalid unsigned tinyint(1) NOT NULL DEFAULT '0'\n" +
            ");",

            "INSERT INTO configuration_lu\n" +
            "SELECT 1 AS id, 'Long' AS configuration_desc, '2014-01-25 15:18:38' AS timestamp, 0 AS invalid\n" +
            "UNION SELECT 2, 'Wide', '2014-01-25 15:18:38', 0\n" +
            "UNION SELECT 3, 'Square', '2014-01-25 15:18:38', 0\n" +
            "UNION SELECT 4, 'Other', '2014-01-25 15:18:38', 0;",

            "CREATE TABLE IF NOT EXISTS event_lu (\n" +
            "	id integer primary key autoincrement,\n" +
            "	event_name text NOT NULL,\n" +
            "	match_url text NOT NULL,\n" +
            "	timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\n" +
            "	invalid unsigned tinyint(1) NOT NULL DEFAULT '0'\n" +
            ");",

            "INSERT INTO event_lu\n" +
            "SELECT 1 AS id, 'Buckeye Regional' AS event_name, 'http://www2.usfirst.org/2014comp/Events/OHCL/ScheduleQual.html' AS match_url, '2014-01-25 15:19:51' AS timestamp, 0 AS invalid\n" +
            "UNION SELECT 2, 'Greater Pittsburgh Regional', 'http://www2.usfirst.org/2014comp/Events/PAPI/ScheduleQual.html', '2014-01-25 15:19:51', 0\n" +
            "UNION SELECT 3, 'Championship - Archimedes', 'http://www2.usfirst.org/2014comp/Events/Archimedes/ScheduleQual.html', '2014-01-25 15:19:51', 0\n" +
            "UNION SELECT 4, 'Championship - Curie', 'http://www2.usfirst.org/2014comp/Events/Curie/ScheduleQual.html', '2014-01-25 15:19:51', 0\n" +
            "UNION SELECT 5, 'Championship - Galileo', 'http://www2.usfirst.org/2014comp/Events/Galileo/ScheduleQual.html', '2014-01-25 15:19:51', 0\n" +
            "UNION SELECT 6, 'Championship - Newton', 'http://www2.usfirst.org/2014comp/Events/Newton/ScheduleQual.html', '2014-01-25 15:19:51', 0;",

            "CREATE TABLE IF NOT EXISTS fact_cycle_data (\n" +
            "	id integer primary key autoincrement,\n" +
            "	event_id unsigned int(5) NOT NULL,\n" +
            "	match_id unsigned int(3) NOT NULL,\n" +
            "	team_id unsigned int(5) NOT NULL,\n" +
            "	cycle_num unsigned int(3) NOT NULL,\n" +
            "	near_poss unsigned tinyint(1) NOT NULL,\n" +
            "	white_poss unsigned tinyint(1) NOT NULL,\n" +
            "	far_poss unsigned tinyint(1) NOT NULL,\n" +
            "	truss unsigned tinyint(1) NOT NULL,\n" +
            "	catch unsigned tinyint(1) NOT NULL,\n" +
            "	high unsigned tinyint(1) NOT NULL,\n" +
            "	low unsigned tinyint(1) NOT NULL,\n" +
            "	assists unsigned int(3) NOT NULL,\n" +
            "	timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\n" +
            "	invalid unsigned tinyint(1) NOT NULL DEFAULT '0'\n" +
            ");",

            "CREATE TABLE IF NOT EXISTS fact_match_data (\n" +
            "	id integer primary key autoincrement,\n" +
            "	event_id unsigned int(5) NOT NULL,\n" +
            "	match_id unsigned int(3) NOT NULL,\n" +
            "	team_id unsigned int(5) NOT NULL,\n" +
            "	auto_high unsigned int(1) NOT NULL,\n" +
            "	auto_high_hot unsigned int(1) NOT NULL,\n" +
            "	auto_low unsigned int(1) NOT NULL,\n" +
            "	auto_low_hot unsigned int(1) NOT NULL,\n" +
            "   assist_points unsigned int(3) NOT NULL,\n" +
            "	high unsigned int(1) NOT NULL,\n" +
            "	low unsigned int(1) NOT NULL,\n" +
            "	truss unsigned int(3) NOT NULL,\n" +
            "	caught unsigned int(3) NOT NULL,\n" +
            "	auto_mobile unsigned tinyint(1) NOT NULL,\n" +
            "	auto_goalie unsigned tinyint(1) NOT NULL,\n" +
            "	num_cycles unsigned int(3) NOT NULL,\n" +
            "	misses unsigned int(3) NOT NULL,\n" +
            "	foul unsigned tinyint(1) NOT NULL,\n" +
            "	tech_foul unsigned tinyint(1) NOT NULL,\n" +
            "	tip_over unsigned tinyint(1) NOT NULL,\n" +
            "	yellow_card unsigned tinyint(1) NOT NULL,\n" +
            "	red_card unsigned tinyint(1) NOT NULL,\n" +
            "	notes text NOT NULL,\n" +
            "	timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\n" +
            "	invalid unsigned tinyint(1) NOT NULL DEFAULT '0'\n" +
            ");",

            "CREATE TABLE IF NOT EXISTS notes_options (\n" +
            "	id integer primary key autoincrement,\n" +
            "	option_text text NOT NULL,\n" +
            "	timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\n" +
            "	invalid unsigned tinyint(1) NOT NULL DEFAULT '0'\n" +
            ");",

            "INSERT INTO notes_options\n" +
            "SELECT 1 AS id, 'No Show' AS option_text, '2014-01-25 15:21:36' AS timestamp, 0 AS invalid\n" +
            "UNION SELECT 2, 'Non-functional', '2014-01-25 15:21:36', 0\n" +
            "UNION SELECT 3, 'Defender', '2014-01-25 15:21:36', 0\n" +
            "UNION SELECT 4, 'Catcher', '2014-01-25 15:21:36', 0;",

            "CREATE TABLE IF NOT EXISTS robot_lu (\n" +
            "	id integer primary key autoincrement,\n" +
            "	team_id unsigned int(5) NOT NULL,\n" +
            "	robot_photo text NOT NULL,\n" +
            "	timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\n" +
            "	invalid unsigned tinyint(1) NOT NULL DEFAULT '0'\n" +
            ");",

            "CREATE TABLE IF NOT EXISTS scout_pit_data (\n" +
            "	id integer primary key autoincrement,\n" +
            "	team_id unsigned int(10) NOT NULL,\n" +
            "	configuration_id unsigned int(10) NOT NULL,\n" +
            "	wheel_type_id unsigned int(10) NOT NULL,\n" +
            "	wheel_base_id unsigned int(10) NOT NULL,\n" +
            "	autonomous_mode tinyint(1) NOT NULL,\n" +
            "	auto_high unsigned tinyint(1) NOT NULL,\n" +
            "	auto_low unsigned tinyint(1) NOT NULL,\n" +
            "	auto_hot unsigned tinyint(1) NOT NULL,\n" +
            "	auto_mobile unsigned tinyint(1) NOT NULL,\n" +
            "	auto_goalie unsigned tinyint(1) NOT NULL,\n" +
            "	truss unsigned tinyint(1) NOT NULL,\n" +
            "	catch unsigned tinyint(1) NOT NULL,\n" +
            "	active_control unsigned tinyint(1) NOT NULL,\n" +
            "	launch_ball unsigned tinyint(1) NOT NULL,\n" +
            "	score_high tinyint(1) NOT NULL,\n" +
            "	score_low tinyint(1) NOT NULL,\n" +
            "	max_height unsigned int(10) NOT NULL,\n" +
            "	scout_comments text NOT NULL,\n" +
            "	timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\n" +
            "	invalid unsigned tinyint(1) NOT NULL DEFAULT '0'\n" +
            ");",

            "CREATE TABLE IF NOT EXISTS wheel_base_lu (\n" +
            "	id integer primary key autoincrement,\n" +
            "	wheel_base_desc text NOT NULL,\n" +
            "	timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\n" +
            "	invalid unsigned tinyint(1) NOT NULL DEFAULT '0'\n" +
            ");",

            "INSERT INTO wheel_base_lu\n" +
            "SELECT 1 AS id, '4 Wheel Drive' AS wheel_base_desc, '2014-01-25 15:23:47' AS timestamp, 0 AS invalid\n" +
            "UNION SELECT 2, '6 Wheel Drive', '2014-01-25 15:23:47', 0\n" +
            "UNION SELECT 3, '8 Wheel Drive+', '2014-01-25 15:23:47', 0\n" +
            "UNION SELECT 4, 'Omnidirectional', '2014-01-25 15:23:47', 0\n" +
            "UNION SELECT 5, 'Other', '2014-01-25 15:23:47', 0;",

            "CREATE TABLE IF NOT EXISTS wheel_type_lu (\n" +
            "	id integer primary key autoincrement,\n" +
            "	wheel_type_desc text NOT NULL,\n" +
            "	timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\n" +
            "	invalid unsigned tinyint(1) NOT NULL DEFAULT '0'\n" +
            ");",

            "INSERT INTO wheel_type_lu\n" +
            "SELECT 1 AS id, 'Kit Wheels' AS wheel_type_desc, '2014-01-25 15:25:39' AS timestamp, 0 AS invalid\n" +
            "UNION SELECT 2, 'Omni', '2014-01-25 15:25:39', 0\n" +
            "UNION SELECT 3, 'Mecanum', '2014-01-25 15:25:39', 0\n" +
            "UNION SELECT 4, 'Tank Tread', '2014-01-25 15:25:39', 0\n" +
            "UNION SELECT 5, 'Swerve', '2014-01-25 15:25:39', 0\n" +
            "UNION SELECT 6, 'Other', '2014-01-25 15:25:39', 0;"
    };

    public static final String[] SQL_DELETE_ENTRIES = {
            "DROP TABLE IF EXISTS configuration_lu;",
            "DROP TABLE IF EXISTS event_lu;",
            "DROP TABLE IF EXISTS fact_cycle_data;",
            "DROP TABLE IF EXISTS fact_match_data;",
            "DROP TABLE IF EXISTS notes_options;",
            "DROP TABLE IF EXISTS robot_lu;",
            "DROP TABLE IF EXISTS scout_pit_data;",
            "DROP TABLE IF EXISTS wheel_base_lu;",
            "DROP TABLE IF EXISTS wheel_type_lu;"
    };

}